site_name: Amusement Park Simulation
nav:
  - Home: index.md
  - About: about.md
  - Games:
    - "Ping Pong": games/ping.md
    - Balloon: games/balloon.md
  - Rides:
    - "Scary Coaster": rides/scary.md
    - "Drop of Doom": rides/drop.md
theme:
  name: material